services:
  - type: web
    name: whatsapp-bot
    env: node
    buildCommand: npm install
    startCommand: node index.js
    plan: free
    healthCheckPath: /
    autoDeploy: true
    disk:
      name: whatsapp-session
      mountPath: /opt/render/project/src
      sizeGB: 1 