services:
  - type: web
    name: whatsapp-bot
    env: node
    plan: free
    autoDeploy: true
    buildCommand: |
      npm install
      pip install -r requirements.txt

    startCommand: |
      node index.js

    healthCheckPath: /

    envVars:
      - key: NODE_ENV
        value: PRODUCTION
      - key: PYTHONUNBUFFERED
        value: 1

    disk:
      name: whatsapp-session
      mountPath: /opt/render/project/src
      sizeGB: 1
